### ISSUE TITLE
bitbucket access denied

### ISSUE THREAD

**Issue by famoser** [lhartikk/lhartikk.github.io#3]
Thanks for the nice tutorial!
In chapter 6, the vue.js UI can not be accessed (Access Denied): https://bitbucket.org/lapanen13/naivecoin-vue
Found on [this line](https://github.com/lhartikk/lhartikk.github.io/blob/a4065a130568cfe6614c2b5c29bc7e1941cba241/jekyll/update/2017/07/09/chapter6.html#L127)

**Comment by lhartikk** [comment]
Thanks for letting me know!

The link should be now fixed
